services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\ReportBuilderBundle\Builder\ReportMenuBuilderInterface:
        class: Kematjaya\ReportBuilderBundle\Builder\ReportMenuBuilder

    Kematjaya\ReportBuilderBundle\Manager\ReportBuilderManagerInterface:
        class: Kematjaya\ReportBuilderBundle\Manager\ReportBuilderManager

    Kematjaya\ReportBuilderBundle\Repository\ReportQueryRepository: ~
    Kematjaya\ReportBuilderBundle\Controller\ReportBuilderController: ~
    Kematjaya\ReportBuilderBundle\Form\ReportQueryType: ~
    Kematjaya\ReportBuilderBundle\Twig\ReportMenuExtension:
        class: Kematjaya\ReportBuilderBundle\Twig\ReportMenuExtension
        tags: ['twig.extension']
